### ISSUE TITLE
[PE-D][Tester A] Unable to set modular credits beyond preset values

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-4/tp#192]
There are NUS modules that have modular credits beyond the range of allowable credits in Modganiser. For example EG3611A Industrial Attachment is worth 10mcs.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: GohJW/ped#2

**Comment by Thiolk** [comment]
Similar bug to issue #202
