### ISSUE TITLE
[PE-D][Tester B] Display issues for printing lists

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-4/tp#193]
As it was not indicated that I have to use this app in full screen, I ran the app with the default terminal size on mac. The list displayed was very messy. I recommend to either just list the semesters one by one or add using the app in full screen to the requirements.

![image.png](https://raw.githubusercontent.com/Stella1585/ped/main/files/083a49d5-77c1-4aae-a5c7-c60c0eb62294.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Stella1585/ped#1

**Comment by Thiolk** [comment]
put in UG use in full screen mode

**Comment by Thiolk** [comment]
PR#246 fixed this issue
