### ISSUE TITLE
[PE-D][Tester C] User guide explaining the edit function can be confusing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-4/tp#195]
### Command Format

The documentation on the command format is clear.

### Accessing a module that doesn't exist in your module plan

The idea of the warning is clear. However the image provided is the following:

![image.png](https://raw.githubusercontent.com/dsicol/ped/main/files/66159446-54dc-4557-87bd-bcfcc9cfd1e2.png)

Above, it was shown that CS2113T (case-insensitive by the application) is in the module list. The image shows the lower case version of the same module and shows that it is not in the module plan. This can be misleading because users may believe that module codes are case sensitive.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: dsicol/ped#2

**Comment by Thiolk** [comment]
Fixed in PR#236
