### ISSUE TITLE
[PE-D][Tester E] module codes that are too long disrupt the list function 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-4/tp#213]
![image.png](https://raw.githubusercontent.com/leonghuenweng/ped/main/files/54d16dd3-30d0-4b89-a1cf-d35ddfd80fcb.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: leonghuenweng/ped#7

**Comment by Thiolk** [comment]
Similar bug in issue #205
