### ISSUE TITLE
[TA] Code Review for Leng Kiat

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2223S2-CS2113T-T09-4/tp#259]
- [x] In `Parser.java` lines 118 to 149 there seems to be deep nesting. Consider refactoring portions of the inner nests to a different function
- [x] Function `checkUserInput` is very long >30 lines. Consider refactoring its contents to multiple different functions
- [x] In `Parser.java` function `trackGraduationRequirements` the case statements have somewhat repeated operations in them. Consider refactoring the application of `listOfModules.trackModules` to outside the switch case at the end, and maybe use a variable to store the REQUIRED_MC for each type? Then you call `listOfModules.trackModules` once using the foundModules & required mc variables? 
- [x] In `ModuleList.java` function `findModuleByType` the case statements have similar operations occuring in them, maybe see if you can refactor out a function to perform this operation

Good job with following the coding standard requirements! 👍🏽

**Comment by Thiolk** [comment]
Fix in PR#266
