### ISSUE TITLE
grade command

### ISSUE THREAD

**Issue by Thiolk** [AY2223S2-CS2113T-T09-4/tp#285]
@denzelcjy we did not state that grade can be used to update a grade. but tbh, we never change the code so like if ppl use grade to edit the existing grade of a module, would it be considered a bug?

**Comment by denzelcjy** [comment]
@Thiolk i do not think it will be a bug, but I agree that there should not be a case where a user gets to grade the modules using the `grade` command when there is already an `edit` function for it. Will update the code and submit a PR to fix this soon! Thanks for pointing this out! 💯
