### ISSUE TITLE
accepted grades

### ISSUE THREAD

**Issue by Thiolk** [AY2223S2-CS2113T-T09-4/tp#289]
![Screenshot 2023-04-06 at 11 05 43 PM](https://user-images.githubusercontent.com/88479051/230420616-ca686f21-93b5-4f81-9bed-1131e7dd2cc1.png)

are we gonna accept this grades as valid inputs?

**Comment by denzelcjy** [comment]
Nope, no intention to accept these grades. A W grade for a module should just be deleted by the user instead, since it is equivalent to dropping and "not taking the module". Furthermore a W grade does not count towards calculation of the CAP as well.
